spring.application.name=EmployeeShift

//DB
spring.datasource.url=jdbc:mysql://localhost:3306/store?serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

//OpenAI
spring.ai.openai.api-key=sk-Lq22zzzlRhBRrERuHdAGlATvE3zaXsC0grWrkLDc9HrqzAwa
spring.ai.openai.base-url=https://api.chatanywhere.org
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7

//ZhiPu
spring.ai.zhipuai.api-key=f82391e39c7947328741cadc2a595945.ULpd9aliCUqVjhSX
spring.ai.zhipuai.image.options.model=CogView-3-Flash



#sql schema ????
#spring.sql.init.schema-locations=classpath:schema-mysql.sql
#[always][embedded][never]
spring.sql.init.mode=always
#sql ??????
#spring.sql.init.data-locations=classpath:data-mysql.sql
#????? table?? schema ? entity ????
#spring.jpa.generate-ddl=false

